### ISSUE TITLE
Cooling enclosure in control room

### ISSUE THREAD

**Issue by vedran-dobos** [astrohr/dagor_tca#31]
Better cooling of the 3-phase motor controllers.

Big hole done on top, and better/stronger fan with protection grill mounted. But fan is not working at the moment.

If possible, use controller (Arduino?) to change fan speed of the fan  (and/or start/stop it) depending on temperature inside.

There is a thermostat/fan module in a shipping container near the dorm. Use that in the beginning maybe?

![img_20160528_224957](https://cloud.githubusercontent.com/assets/19259909/15631750/8a028558-2579-11e6-83b7-e1414e07fb5d.jpg)
![img_20160528_224950](https://cloud.githubusercontent.com/assets/19259909/15631751/8a044dfc-2579-11e6-8788-599ca6e1d450.jpg)

**Comment by frnhr** [comment]
Mounted two fans, and a dist filter to prevent stuff falling in because stepper drivers are directly below the vent. The two fans are connected in series on 12V. Noise level is fairly low this way (about 45 db near the PC monitor). Connecting them to 15V increases noise level to 50db. We are probably ok with 12V though, with respect to cooling. Max temperature inside the enclosure was 27ºC, after several minutes of full-speed teleskope movements.

![img_1208](https://cloud.githubusercontent.com/assets/1173748/15635446/bd1b66de-25de-11e6-8888-712fea7160e8.jpg)

Also cleared metal debris inside the drivers. Nothing much, but there were some very fine chips in, almost dust. 
If you always wanted to know what is inside those driver, but were afraid to ask:
![img_1206](https://cloud.githubusercontent.com/assets/1173748/15635456/e7593a20-25de-11e6-8254-ecf261de6ba4.jpg)
![img_1207](https://cloud.githubusercontent.com/assets/1173748/15635490/b12a7ec2-25df-11e6-98c1-9492da246e3a.jpg)

**Comment by frnhr** [comment]
Todo:

- [ ] better PCB for voltage regulators inside the breaker box (currently it's a breadboard)

**Comment by frnhr** [comment]
Proto-PCB is ready:
![screenshot_30_05_16_18_56](https://cloud.githubusercontent.com/assets/1173748/15654887/32f0c89a-2698-11e6-97a4-c77b899c1684.png)


Nothing special here, a voltage regulator and two connectors for fans, in series. Two "features:
 * Jumpers can be set so that fans are connected in parallel or in series (photo shows config for series)
 * Voltage regulator is plugged in a 3-pin header, and is removeable. Any 78xx will do. Input is 24V.

Drawing a schematics is probably an overkill. But a nice label would be neat...

 - [ ] Mount it inside the breaker box
